version = 0.1

[dev]
[dev.global.parameters]
stack_name          = "tsuru-dev-api-gateway"
s3_bucket           = "tsuru-dev-sam-deployments"
s3_prefix           = "tsuru-api-gateway"
region              = "us-east-1"
confirm_changeset   = false
capabilities        = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev HostedZoneId=Z05336353K95HTG1OQ5PH DomainName=api.tsuru.jcampos.dev"

[stag]
[stag.global.parameters]
stack_name          = "tsuru-stag-api-gateway"
s3_bucket           = "tsuru-stag-sam-deployments"
s3_prefix           = "tsuru-api-gateway"
region              = "us-east-1"
confirm_changeset   = false
capabilities        = "CAPABILITY_IAM"
parameter_overrides = "Environment=stag HostedZoneId=Z05336353K95HTG1OQ5PH DomainName=api.tsuru.jcampos.dev"

[prod]
[prod.global.parameters]
stack_name          = "tsuru-prod-api-gateway"
s3_bucket           = "tsuru-prod-sam-deployments"
s3_prefix           = "tsuru-api-gateway"
region              = "us-east-1"
confirm_changeset   = false
capabilities        = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod HostedZoneId=Z05336353K95HTG1OQ5PH DomainName=api.tsuru.jcampos.dev"
