#!/usr/bin/env python3
"""Sync the shared email theme into independently deployed services and SES HTML."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
css = (ROOT / 'docs/brand/email-theme.css').read_text()
rules = json.loads((ROOT / 'docs/brand/email-theme.json').read_text())
python_source = '''"""Generated by scripts/sync-email-theme.py; keep light-mode inline fallbacks."""
import re

CSS = __CSS__
RULES = __RULES__
ARTWORK = {
    'email-header.png': 'email-header-dark.png',
    'email-footer-waves-compact.png': 'email-footer-waves-dark.png',
}


def _classes(tag):
    style = re.search(r'\\bstyle="([^"]*)"', tag, re.I)
    if not style:
        return tag
    declarations = dict((key.strip().lower(), value.strip().lower())
                        for key, value in re.findall(r'([\\w-]+)\\s*:\\s*([^;]+)', style.group(1)))
    classes = []
    for prop, values in RULES.items():
        value = declarations.get(prop)
        if value in values:
            classes.append(values[value][0])
    if any(key.startswith('border') and ('#e5dccf' in value or '#f4efe6' in value)
           for key, value in declarations.items()):
        classes.append('ts-border')
    if not classes:
        return tag
    existing = re.search(r'\\bclass="([^"]*)"', tag, re.I)
    if existing:
        merged = list(dict.fromkeys(existing.group(1).split() + classes))
        return tag[:existing.start(1)] + ' '.join(merged) + tag[existing.end(1):]
    return re.sub(r'^(<[^\\s>]+)', lambda m: m.group(1) + ' class="' + ' '.join(classes) + '"', tag)


def _artwork(tag):
    if not re.match(r'<img\\b', tag, re.I):
        return tag
    for light, dark in ARTWORK.items():
        if '/' + light not in tag:
            continue
        light_tag = re.sub(r'\\bclass="([^"]*)"', lambda m: 'class="' + m.group(1) + ' ts-art-light"', tag) if re.search(r'\\bclass="', tag) else tag.replace('<img', '<img class="ts-art-light"', 1)
        dark_tag = tag.replace('/' + light, '/' + dark)
        dark_tag = re.sub(r'\\bclass="([^"]*)"', lambda m: 'class="' + m.group(1) + ' ts-art-dark"', dark_tag) if re.search(r'\\bclass="', dark_tag) else dark_tag.replace('<img', '<img class="ts-art-dark"', 1)
        dark_tag = dark_tag.replace('display:block;', 'display:none;').replace('display: block;', 'display:none;')
        dark_tag = dark_tag.replace('style="', 'style="max-height:0;overflow:hidden;mso-hide:all;', 1)
        return light_tag + dark_tag
    return tag


def apply_email_theme(html):
    """Add progressive dark-mode support; content and light inline styles stay intact."""
    if 'id="tsuru-email-theme"' in html:
        return html
    html = re.sub(r'(<meta\\s+name="(?:color-scheme|supported-color-schemes)"\\s+content=")light("\\s*/?>)',
                  r'\\1light dark\\2', html, flags=re.I)
    html = re.sub(r'<[a-z][^>]*>', lambda m: _artwork(_classes(m.group(0))), html, flags=re.I)
    return html.replace('</head>', '<style id="tsuru-email-theme">\\n' + CSS + '</style>\\n</head>', 1)
'''.replace('__CSS__', repr(css)).replace('__RULES__', repr(rules))
for dest in ['be/sales-be/shared/jbiller_common/hacienda/templates/email_theme.py',
             'be/store-be/app/services/email_theme.py']:
    (ROOT / dest).write_text(python_source)

ts_source = '''// Generated by scripts/sync-email-theme.py; keep light-mode inline fallbacks.
const CSS = __CSS__;
const RULES: Record<string, Record<string, [string, string]>> = __RULES__;
const ARTWORK: Record<string, string> = {
  'email-header.png': 'email-header-dark.png',
  'email-footer-waves-compact.png': 'email-footer-waves-dark.png',
};

function themeTag(tag: string): string {
  const style = tag.match(/\\bstyle="([^"]*)"/i)?.[1];
  const classes: string[] = [];
  if (style) {
    const declarations: Record<string, string> = {};
    for (const match of Array.from(style.matchAll(/([\\w-]+)\\s*:\\s*([^;]+)/g))) {
      declarations[match[1].trim().toLowerCase()] = match[2].trim().toLowerCase();
    }
    for (const [prop, values] of Object.entries(RULES)) {
      const rule = values[declarations[prop]];
      if (rule) classes.push(rule[0]);
    }
    if (Object.entries(declarations).some(([key, value]) => key.startsWith('border') && /#e5dccf|#f4efe6/.test(value))) classes.push('ts-border');
    if (classes.length) {
      if (/\\bclass="/i.test(tag)) tag = tag.replace(/\\bclass="([^"]*)"/i, (_, value: string) => `class="${Array.from(new Set([...value.split(/\\s+/), ...classes])).join(' ')}"`);
      else tag = tag.replace(/^(<[^\\s>]+)/, `$1 class="${classes.join(' ')}"`);
    }
  }
  if (!/^<img\\b/i.test(tag)) return tag;
  for (const [light, dark] of Object.entries(ARTWORK)) {
    if (!tag.includes('/' + light)) continue;
    const addClass = (image: string, name: string): string => /\\bclass="/i.test(image)
      ? image.replace(/\\bclass="([^"]*)"/i, (_, value: string) => `class="${value} ${name}"`)
      : image.replace(/^(<img)/i, `$1 class="${name}"`);
    const lightTag = addClass(tag, 'ts-art-light');
    const darkTag = addClass(tag.replace('/' + light, '/' + dark), 'ts-art-dark')
      .replace(/display:\\s*block;/, 'display:none;')
      .replace('style="', 'style="max-height:0;overflow:hidden;mso-hide:all;');
    return lightTag + darkTag;
  }
  return tag;
}

export function applyEmailTheme(html: string): string {
  if (html.includes('id="tsuru-email-theme"')) return html;
  return html.replace(/(<meta\\s+name="(?:color-scheme|supported-color-schemes)"\\s+content=")light("\\s*\\/?>)/gi, '$1light dark$2')
    .replace(/<[a-z][^>]*>/gi, match => themeTag(match))
    .replace('</head>', `<style id="tsuru-email-theme">\\n${CSS}</style>\\n</head>`);
}
'''.replace('__CSS__', json.dumps(css)).replace('__RULES__', json.dumps(rules))
(ROOT / 'be/management-be/src/templates/emailTheme.ts').write_text(ts_source)

# Rebuild static Cognito HTML from its light fallback, so regeneration is idempotent.
namespace = {}
exec(compile(python_source, '<email_theme>', 'exec'), namespace)
import re
for path in (ROOT / 'be/cognito-templates/ses/templates').glob('*.html'):
    html = path.read_text()
    html = re.sub(r'<style id="tsuru-email-theme">.*?</style>\s*', '', html, flags=re.S)
    html = re.sub(r'<img[^>]*class="[^"]*ts-art-dark[^"]*"[^>]*>', '', html)
    html = re.sub(r' class="ts-[^"]*"', '', html)
    html = html.replace('content="light dark"', 'content="light"')
    path.write_text(namespace['apply_email_theme'](html))
print('Synchronized light/dark styles, artwork switching and Cognito templates')
